version: '3'

services:
  web:
    container_name: dev_backend
    build: 
      context: ../
      dockerfile: deploy/Dockerfile
    restart: always
    volumes:
     - ../src:/app
     - static_volume:/app/static
    ports:
      - "127.0.0.1:8000:8000"
    environment:
      DEBUG: ${DEBUG}
      SECRET_KEY: ${SECRET_KEY}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    depends_on:
     - db

  db:
    container_name: dev_db
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432

volumes:
  static_volume:
  postgres_data:
